import { Footer, Navbar } from '@/components';
import { Providers } from '@/providers';
import '@/styles/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Portfolio',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body>
				<Providers>
					<Navbar />

					{children}
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
